name: Build and release

on:
  push:
    branches:
      - master

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Grant permission for scripts
        run: chmod +x ./scripts/*.sh

      - name: Check should release
        id: release
        run: ./scripts/release_check.sh

      - name: set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build apks
        run: ./gradlew assembleRelease --scan
        env:
          PASSWORD: "${{ secrets.PASSWORD }}"
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

      - name: Build aab
        if: steps.release.outputs.release == 'true'
        run: ./gradlew bundlePlayRelease --scan
        env:
          PASSWORD: "${{ secrets.PASSWORD }}"
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

      - name: PreRelease Package
        if: steps.release.outputs.release == 'false'
        run: |
          gh release delete nightly --cleanup-tag --yes || true
          gh release create nightly \
            app/build/outputs/apk/github/release/* \
            app/build/outputs/apk/free/release/app-free-release.apk \
            --target "$GITHUB_SHA" \
            --title "nightly" \
            --notes "Nightly build" \
            --prerelease \
            --latest=false
        env:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"

      - name: Release Package
        if: steps.release.outputs.release == 'true'
        run: |
          gh release create "${{ steps.release.outputs.version }}" \
            app/build/outputs/apk/github/release/* \
            app/build/outputs/apk/free/release/app-free-release.apk \
            app/build/outputs/bundle/playRelease/app-play-release.aab \
            --target "$GITHUB_SHA" \
            --title "${{ steps.release.outputs.version }}" \
            --notes "Release ${{ steps.release.outputs.version }}"
        env:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"

      - name: Create whatsNew
        if: steps.release.outputs.release == 'true'
        run: |
            ./scripts/whats_new.sh
        env:
          VERSION: ${{ steps.release.outputs.version }}

      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.1.5
        if: steps.release.outputs.release == 'true'
        with:
          releaseFiles: app/build/outputs/bundle/playRelease/app-play-release.aab
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: top.learningman.push
          track: beta
          mappingFile: app/build/outputs/mapping/playRelease/mapping.txt
          whatsNewDirectory: whatsNew
